-- (H2)
DROP TABLE IF EXISTS reservation_post;
DROP TABLE IF EXISTS reservation;
DROP TABLE IF EXISTS forestilling;
DROP TABLE IF EXISTS sal;
DROP TABLE IF EXISTS film;

CREATE TABLE film (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titel              VARCHAR(255) NOT NULL,
  varighed_minutter  INT NOT NULL CHECK (varighed_minutter > 0)
);

CREATE TABLE sal (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  navn       VARCHAR(255) NOT NULL,
  kapacitet  INT NOT NULL CHECK (kapacitet > 0)
);

CREATE TABLE forestilling (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id    BIGINT NOT NULL,
  sal_id     BIGINT NOT NULL,
  start_tid  TIMESTAMP NOT NULL,
  CONSTRAINT fk_forestilling_film FOREIGN KEY (film_id) REFERENCES film(id),
  CONSTRAINT fk_forestilling_sal  FOREIGN KEY (sal_id)  REFERENCES sal(id)
);

CREATE TABLE reservation (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  oprettet_tid  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE reservation_post (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id  BIGINT NOT NULL,
  forestilling_id BIGINT NOT NULL,
  antal_pladser   INT NOT NULL CHECK (antal_pladser > 0),
  CONSTRAINT fk_rp_reservation  FOREIGN KEY (reservation_id)  REFERENCES reservation(id) ON DELETE CASCADE,
  CONSTRAINT fk_rp_forestilling FOREIGN KEY (forestilling_id) REFERENCES forestilling(id)
);

CREATE INDEX idx_forestilling_start_tid ON forestilling (start_tid);
CREATE INDEX idx_rp_forestilling_id ON reservation_post (forestilling_id);
